### ISSUE TITLE
Trying to call function from rust

### ISSUE THREAD

**Issue by ghosty2004** [zhangyuang/node-ffi-rs#10]
Hello. I'm trying to call a function from rust (it's a dynamic library), but it's not working properly.

# My files for rust
`src/lib.rs`:
```rust
#[no_mangle]
pub extern "C" fn sum(a: i32, b: i32) -> i32 {
    a + b
}
```
`Cargo.toml`:
```toml
[package]
name = "the-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
```

# The nodejs script
```js
const p = require("ffi-rs");

const r = p.load({
  library: "./the-lib/target/release/the_lib.dll",
  funcName: "sum",
  retType: p.DataType.I32,
  paramsType: [p.DataType.I32, p.DataType.I32],
  paramsValue: [10, 10],
});

console.log("result", r);
```

This is the error what I receive when I start my node app:
```
thread '<unnamed>' panicked at src\lib.rs:75:35:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Versions
```
node: v18.0.0
rustc: rustc 1.72.1 (d5c2e9c34 2023-09-13)
```
